### ISSUE TITLE
Windows app still shuts down 0.4.1

### ISSUE THREAD

**Issue by vindberg** [cosmos/cosmos-ui#442] opened 2018-02-03 12:48 UTC
Hi guys, just tried the latest release of the windows version, it looks like its still shutting down immediately after startup.

The version fil says its this version: v1.8.1.

Im not seeing any exceptions in the eventlog or any other logfile.

#436

**Comment by faboweb** [comment] 2018-02-03 18:20
Thank you for sending in this issue.
Sadly I can't reproduce the issue.

The actual app versions are stored in `%USER_DIR%/.Cosmos` (for me `C:\Users\Fabo\.Cosmos`). Could you post the content of `app_version`?

Could we maybe also try sth.: Could you backup `%USER_DIR%/.Cosmos` and then remove it and afterwards restart the application?

Additionally I will add better logging so we can get to the root of this.

**Comment by vindberg** [comment] 2018-02-03 18:49
Hi, the version file in the user folder says: 0.4.1

The log was also in that folder. Looks like a connection error:

`Sat Feb 03 2018 12:31:06 GMT+0100 (W. Europe Standard Time) Running Cosmos-UI
main-process: initializing data directory (C:\Users\***\.Cosmos)
main-process: starting app
main-process: dev mode: false
main-process: winURL: file://D:\Software\Wallets\Cosmos-win32-x64_0.4.1\resources\app\dist/index.html
main-process: spawning D:\Software\Wallets\Cosmos-win32-x64_0.4.1\resources\app\bin\gaia.exe with args ""version""
main-process: gaia.exe: v0.5.0

main-process: gaia version: "v0.5.0", expected: "v0.5.0"
main-process: Picked seed: 159.203.88.224:46656 of 178.62.35.120:46656,138.68.21.243:46656,159.203.88.224:46656,138.197.131.102:46656,95.85.37.158:46656,159.89.3.34:46656
main-process: Initializing baseserver with remote node 159.203.88.224:46657
main-process: spawning D:\Software\Wallets\Cosmos-win32-x64_0.4.1\resources\app\bin\gaia.exe with args ""client" "init" "--home" "C:\\Users\\***\\.Cosmos\\baseserver" "--chain-id" "gaia-2" "--node" "159.203.88.224:46657""
main-process: gaia.exe exited with code 0
main-process: gaia.exe: Loading validator set from tendermint rpc...

main-process: gaia.exe: ERROR: Status: Post http://159.203.88.224:46657: dial tcp 159.203.88.224:46657: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

main-process: gaia.exe exited with code 1
`
Hope it can help you.

**Comment by vindberg** [comment] 2018-02-03 18:50
I get a "Deceptive site ahead" warning in Chrome when I go to the IP from above: http://159.203.88.224:46657/

**Comment by faboweb** [comment] 2018-02-03 18:52
Thanks a lot for the support. This helps us to improve the UI.

**Comment by mappum** [comment] 2018-02-03 19:00
>I get a "Deceptive site ahead" warning in Chrome when I go to the IP from above: http://159.203.88.224:46657/

Very strange, this is just one of our nodes on AWS.  Do you mind posting the output you get from `curl http://159.203.88.224:46657/status`?

**Comment by vindberg** [comment] 2018-02-05 14:16
Is running fine from the console or IE returning this (its only Firefox and Chrome that give the warning)(pub_key minimized):
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "pub_key": "******35993328B127D78809C6A1",
      "moniker": "159.203.88.224",
      "network": "gaia-2",
      "remote_addr": "",
      "listen_addr": "159.203.88.224:46656",
      "version": "0.15.0-381fe19",
      "other": [
        "wire_version=0.7.2",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
        "tx_index=on",
        "rpc_addr=tcp://0.0.0.0:46657"
      ]
    },
    "pub_key": {
      "type": "ed25519",
      "data": "****62D6E75245D885EAAD14"
    },
    "latest_block_hash": "6B7BE1A4C5FD71FC9993FA296E4D6CC909DB3BFD",
    "latest_app_hash": "A749A8179874B2A5EEB408138745ABB14DC7744A",
    "latest_block_height": 1470060,
    "latest_block_time": "2018-02-05T09:13:05.36-05:00",
    "syncing": false
  }

**Comment by faboweb** [comment] 2018-02-05 14:28
The node appears to work again. Is the UI still failing?

**Comment by vindberg** [comment] 2018-02-05 14:37
Its running as two processes in the background called "Cosmos". The user dir/.Cosmos is just empty (after I deleted it to get new stats).

**Comment by faboweb** [comment] 2018-02-05 14:41
If the UI doesn't show, then these appear to be orphaned processes. Could you terminate them and try again?

**Comment by vindberg** [comment] 2018-02-05 14:52
If I kill all Cosmos processes, and then run exe, two new are created. One
using 3 mb and another using about 30 mb.


Anders Vindberg

Director, Advertisement
Http://lunarmedia.com <http://lunarmedia.com>

**Comment by faboweb** [comment] 2018-02-07 09:59
Hi Anders,
currently non of the core developers can reproduce your issue. Therefor I will close this issue. As mentioned we will add better logging in the future to be better able to debug this issue for you. But currently debugging this would mean to much effort.
If you want to try the UI anyway, I would like to point you to the Linux release you could try out in a VM.

Thank you for your understanding.

**Closed by faboweb** 2018-02-07 09:59 UTC
Labels: bug
